on:
  push:
    branches:
      - master
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Shadowjar
        run: ./gradlew shadowJar
      - name: Publish Fat Jar
        uses: actions/upload-artifact@v3
        with:
          name: rsskt.jar
          path: build/libs/rsskt.jar

